### ISSUE TITLE
"The following plugin is ready to update: Require.js plugin" unable to update 

### ISSUE THREAD

**Issue by davidgorges** [Fedott/WebStormRequireJsPlugin#46]
Probably related to #41:  PHPStorm 8.0.3 keeps on displaying this notification. Updating the plugin does not work. Theres nothing in the event log besides:

`` 
10:34:38 Update Info: The following plugin is ready to update: Require.js plugin
``

**Comment by Fedott** [comment]
Hi!
For fix this problem you can install plugin from file https://github.com/Fedott/WebStormRequireJsPlugin/raw/master/requirejs-since-build-139.jar
This version special builded for old version IDEA platform, and should work on you.

In this moment I dont know how build plugin for any version IDEA platform.

**Comment by theNailz** [comment]
PHPStorm __8.0.3__ is the current __stable__ release, which display this notification. Maybe some other developer could tell you how to make two release channels, one for stable and one for beta? Because I get this notification every time I start my PHPStorm, and it annoys me.

**Comment by Fedott** [comment]
For fix your problem:
Download file https://github.com/Fedott/WebStormRequireJsPlugin/raw/master/requirejs-since-build-139.jar
In PhpStorm open Settings -> plugins, click install plugin from disk, select downloaded file, and click "ok"
After this actions you will not get this notification.
